### ISSUE TITLE
Upgrade to version 3.1.0 of sauce connect

### ISSUE THREAD

**Issue by ghost** [sauce-archives/sauce-connect-composer#4]
Hi,

SauceLabs have now released version 3.1.0 of sauce connect to address the heart bleed vulnerability in openssl.

Would it be possible to release a new version of this library that includes this?

Are there any plans to release a version for sauce connect 4.x too?

Thanks,

Matt

**Comment by jlipps** [comment]
This has already been updated! https://packagist.org/packages/sauce/connect
